apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: order-configuration
spec:
  tracing:
    samplingRate: "1"
    # misleading. But zipkin name is used for both jaeger and zipkin endpoints
    zipkin:
      endpointAddress: "http://jaeger-collector.observability.svc.cluster.local:9411/api/v2/spans"
