apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-created-subscription
spec:
  topic: order-created
  pubsubname: order
  routes:
    default: /order-created
scopes:
- dapr-consumer-notification
- dapr-consumer-billing