apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: azure-order-secret
      key: connection-string